# Generated by Django 5.2.7 on 2025-10-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('staff', 'shift', 'date')},
        ),
    ]
